@include('CrudeCRUD::partials.alert')
@include('CrudeCRUD::partials.modal')

@include('CrudeCRUD::action-button')
@include('CrudeCRUD::column-format')
@include('CrudeCRUD::list')
@include('CrudeCRUD::input')
@include('CrudeCRUD::rich-filters-templates')
@include('CrudeCRUD::rich-filters')
@include('CrudeCRUD::modules.form')
@include('CrudeCRUD::modules.map')
@include('CrudeCRUD::modules.file')
@include('CrudeCRUD::modules.thumbnail')
@include('CrudeCRUD::layout')
@include('CrudeCRUD::form-layout')
